### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subtivity-substreams#8]
![telegram-cloud-photo-size-1-5118601586988395162-y](https://user-images.githubusercontent.com/550895/217311768-d9595efb-e4e3-409a-a425-cf20e3b49bb2.jpg)

![telegram-cloud-photo-size-1-5118601586988395163-y](https://user-images.githubusercontent.com/550895/217311794-3b2b6a93-8f39-4ca5-9b14-cd8fd88dabb1.jpg)

![telegram-cloud-photo-size-1-5118601586988395164-y](https://user-images.githubusercontent.com/550895/217311814-372f76bb-e50a-464f-991e-bf3af32f8280.jpg)

![telegram-cloud-photo-size-1-5118601586988395165-y](https://user-images.githubusercontent.com/550895/217311850-9da02a3b-c6a5-4134-ae3e-d984d00baa9e.jpg)

**Comment by DominicF96** [comment]
# Socials

**Homepage Preview**

![Twitter - Home Preview](https://user-images.githubusercontent.com/36671850/225031591-a65491c7-1b27-417c-8dd1-9247bd29770d.png)
![Facebook-LinkedIn - Home Preview](https://user-images.githubusercontent.com/36671850/225031594-3f456740-6ff0-476b-ab80-560cbff80793.png)
![Instagram - Home Preview](https://user-images.githubusercontent.com/36671850/225031597-e36f7811-f4b5-486d-8ca9-b902e0657060.png)

**Network Details Preview**

![LinkedIn - Network Details Preview](https://user-images.githubusercontent.com/36671850/225031747-c5648ba5-06c8-41d6-b465-b5991fb0fbc0.png)
![Facebook-LinkedIn - Network Details Preview](https://user-images.githubusercontent.com/36671850/225031751-cd4d02dc-7cf6-406c-a354-0169a8f1df65.png)
![Instagram - Network Details Preview](https://user-images.githubusercontent.com/36671850/225031752-d1219366-78cd-420f-af76-8ad72cc12f59.png)
